[workspace]
members = ["day01"]
resolver = "3"

[workspace.dependencies]
itertools = "0.14.0"
rayon = "1.10.0"
thiserror = "2.0.11"

[workspace.dependencies.criterion]
version = "0.8.0"
features = ["html_reports"]
